"""cipher 密钥派生：硬编码回退密钥移除（Batch 80 / C79-1 / Batch 37 P1-01）。"""

import pytest

from app.core import cipher
from app.core.config import Settings


def _inject_settings(monkeypatch, *, environment: str, secret_key: str) -> Settings:
    """注入隔离的 Settings 实例，避免污染全局单例（monkeypatch 自动还原）。"""
    s = Settings(_env_file=None, environment=environment, secret_key=secret_key)
    monkeypatch.setattr(cipher, "settings", s)
    return s


def test_cipher_roundtrip_uses_effective_key(monkeypatch):
    _inject_settings(monkeypatch, environment="production", secret_key="test-secret-key-0123456789")
    ct = cipher.encrypt_value("sensitive-token")
    assert cipher.decrypt_value(ct) == "sensitive-token"


def test_cipher_dev_autogenerated_key_roundtrip(monkeypatch):
    _inject_settings(monkeypatch, environment="development", secret_key="")
    ct = cipher.encrypt_value("dev-value")
    assert cipher.decrypt_value(ct) == "dev-value"


def test_cipher_production_without_key_fails_loudly(monkeypatch):
    _inject_settings(monkeypatch, environment="production", secret_key="")
    with pytest.raises(RuntimeError, match="SECRET_KEY 未配置"):
        cipher.encrypt_value("x")


def test_cipher_no_hardcoded_fallback():
    # 回归：源码不得包含固定回退密钥
    assert "cameltv-dev-key" not in open(cipher.__file__, encoding="utf-8").read()
