"""测试文件生成器：EndpointSpec → TypeScript Playwright 测试文件。

产出结构:
  tests/api-testing/generated/
    playwright.config.ts            ← Playwright 配置（baseURL/env/proxy）
    <tag>/
      <method>-<path-slug>.spec.ts  ← 接口测试文件，头部标 // source: swagger|ui-capture

每个测试文件包含:
  - test.describe.configure({ retries: 2 })
  - 正向用例（合法参数）
  - 入参校验用例（空值/缺参/非法值）
  - 断言块（状态码/字段/schema/DB）
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from tools.api_tester.swagger_parser import EndpointSpec
from tools.api_tester.assertion_builder import AssertionBuilder


class TestGenerator:
    """将 EndpointSpec 列表生成 TypeScript Playwright 测试工程。"""

    def __init__(self, out_dir: str = "tests/api-testing/generated"):
        self.out_dir = Path(out_dir)
        self.assertion = AssertionBuilder()

    def generate(self, endpoints: list[EndpointSpec], source: str = "swagger") -> int:
        """生成所有测试文件，返回生成的文件数。"""
        self.out_dir.mkdir(parents=True, exist_ok=True)

        count = 0
        for ep in endpoints:
            self._write_test_file(ep, source)
            count += 1

        # 生成/更新 playwright.config.ts
        self._ensure_config()

        return count

    def _write_test_file(self, ep: EndpointSpec, source: str) -> None:
        """为单个接口写 .spec.ts 文件。"""
        tag = ep.tags[0] if ep.tags else "general"
        tag_dir = self.out_dir / self._safe_name(tag)
        tag_dir.mkdir(parents=True, exist_ok=True)

        path_slug = self._path_to_slug(ep.path)
        filename = f"{ep.method.lower()}-{path_slug}.spec.ts"
        filepath = tag_dir / filename

        content = self._render_test_file(ep, source)
        filepath.write_text(content, encoding="utf-8")

    @staticmethod
    def _build_injection(ep: EndpointSpec) -> str:
        """构造非法参数注入：GET→query，POST/PUT/PATCH→body。"""
        if ep.method.upper() in ("POST", "PUT", "PATCH") and ep.request_body:
            return "{ data: { injected: \"' OR '1'='1\" } }"
        return "{ params: { injected: \"' OR '1'='1\" } }"

    def _render_test_file(self, ep: EndpointSpec, source: str) -> str:
        """渲染单个 .spec.ts 文件内容。"""
        tc_id = self._to_test_id(ep)
        assertion_block = self.assertion.build(ep)
        injection = self._build_injection(ep)

        return f"""// source: {source}
// endpoint: {ep.method} {ep.path}
// summary: {ep.summary or '(no description)'}
// generated by tp api pull

import {{ test, expect }} from '@playwright/test';

const BASE_URL = process.env.CAMELTV_BASE_URL || 'http://localhost:8000';

test.describe('{ep.method} {ep.path}', () => {{
  test.describe.configure({{ retries: 2 }});

  test('{tc_id}-001: 正向请求 — 合法参数', async ({{ request }}) => {{
    const response = await request.{ep.method.lower()}(
      `${{BASE_URL}}{ep.path}`{self._build_params(ep)}{self._build_body(ep)}
    );
{assertion_block}
  }});

  test('{tc_id}-002: 入参校验 — 缺少必填参数', async ({{ request }}) => {{
    const response = await request.{ep.method.lower()}(
      `${{BASE_URL}}{ep.path}`
    );
    // 期望：400 Bad Request | 422 Validation Error
    expect(response.status()).toBeGreaterThanOrEqual(400);
  }});

  test('{tc_id}-003: 入参校验 — 非法参数值', async ({{ request }}) => {{
    const response = await request.{ep.method.lower()}(
      `${{BASE_URL}}{ep.path}`,
      {injection}
    );
    // 期望：400/422（被网关拒绝）或 200（安全过滤后正常返回）
    expect([200, 400, 422]).toContain(response.status());
  }});
}});
"""

    @staticmethod
    def _build_params(ep: EndpointSpec) -> str:
        """构造 Playwright request 的 params/headers 参数。"""
        query_params = [p for p in ep.parameters if p.get("in") == "query"]
        if not query_params:
            return ""

        params_obj = {}
        for p in query_params:
            name = p.get("name", "")
            schema = p.get("schema", {})
            example = schema.get("example", schema.get("default", "X"))
            params_obj[name] = example

        if not params_obj:
            return ""

        import json
        return f",\n      {{ params: {json.dumps(params_obj, indent=6)} }}"

    @staticmethod
    def _build_body(ep: EndpointSpec) -> str:
        """构造 Playwright request 的 data 参数（POST/PUT/PATCH）。"""
        if ep.method.upper() not in ("POST", "PUT", "PATCH"):
            return ""
        if not ep.request_body:
            return ""

        content = ep.request_body.get("content", {})
        json_content = content.get("application/json", {})
        schema = json_content.get("schema", {})
        props = schema.get("properties", {})

        if not props:
            return ""

        import json
        body = {}
        for name, spec in props.items():
            example = spec.get("example", spec.get("default", "X"))
            body[name] = example

        return f",\n      {{ data: {json.dumps(body, indent=6)} }}"

    def _ensure_config(self) -> None:
        """确保 Playwright config + tsconfig + package.json 文件存在。"""
        # playwright.config.ts
        config_path = self.out_dir / "playwright.config.ts"
        if not config_path.exists():
            config_path.write_text("""import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './',
  testMatch: '**/*.spec.ts',
  retries: 1,
  timeout: 30000,
  expect: { timeout: 10000 },
  // outputFile 优先读取 runner 注入的绝对路径（JUNIT_OUTPUT / JSON_OUTPUT），
  // 未注入时回退到相对路径（手动 npx playwright test 时仍可用）
  reporter: [
    ['list'],
    ['junit', { outputFile: process.env.JUNIT_OUTPUT || '../../api-testing/reports/api-test-junit.xml' }],
    ['json', { outputFile: process.env.JSON_OUTPUT || '../../api-testing/reports/api-test-results.json' }],
  ],
  use: {
    baseURL: process.env.CAMELTV_BASE_URL || 'http://localhost:8000',
    extraHTTPHeaders: {
      'Authorization': `Bearer ${process.env.CAMELTV_AUTH_TOKEN || ''}`,
    },
    proxy: process.env.HTTP_PROXY ? {
      server: process.env.HTTP_PROXY,
    } : undefined,
    trace: 'on-first-retry',
  },
});
""", encoding="utf-8")

        # tsconfig.json — TypeScript 编译检查用
        tsconfig_path = self.out_dir / "tsconfig.json"
        if not tsconfig_path.exists():
            tsconfig_path.write_text("""{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "esModuleInterop": true,
    "strict": true,
    "noEmit": true,
    "skipLibCheck": true,
    "types": ["node"]
  },
  "include": ["**/*.spec.ts", "playwright.config.ts"]
}
""", encoding="utf-8")

        # package.json — 声明依赖（实际安装由 CI/Docker 完成）
        pkg_path = self.out_dir / "package.json"
        if not pkg_path.exists():
            import json as _json
            pkg_path.write_text(_json.dumps({
                "name": "cameltv-api-tests",
                "private": True,
                "description": "CamelTv API 测试 — Playwright 自动生成",
                "devDependencies": {
                    "@playwright/test": "^1.45",
                    "@types/node": "^20",
                    "typescript": "^5"
                },
                "scripts": {
                    "test": "npx playwright test",
                    "typecheck": "npx tsc --noEmit"
                }
            }, indent=2) + "\n", encoding="utf-8")

    @staticmethod
    def _safe_name(s: str) -> str:
        return re.sub(r"[^a-zA-Z0-9_-]", "-", s).strip("-") or "general"

    @staticmethod
    def _path_to_slug(path: str) -> str:
        return re.sub(r"[{}]", "", path.replace("/", "-").strip("-")) or "root"

    @staticmethod
    def _to_test_id(ep: EndpointSpec) -> str:
        tag = ep.tags[0] if ep.tags else "API"
        return f"API-TC-{tag.upper()}-{ep.method}"
