/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 账号密码登录 */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户信息 */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户可见项目 */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 校验并返回当前项目（需 X-Project-Id） */
        get: operations["current_project_api_v1_projects_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户可见菜单 */
        get: operations["menus_api_v1_system_menus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用户列表 */
        get: operations["list_users_api_v1_system_users_get"];
        put?: never;
        /** 新建用户 */
        post: operations["create_user_api_v1_system_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用户详情 */
        get: operations["get_user_api_api_v1_system_users__user_id__get"];
        /** 更新用户 */
        put: operations["update_user_api_api_v1_system_users__user_id__put"];
        post?: never;
        /** 删除用户 */
        delete: operations["delete_user_api_api_v1_system_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 角色列表 */
        get: operations["list_roles_api_v1_system_roles_get"];
        put?: never;
        /** 新建角色 */
        post: operations["create_role_api_v1_system_roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 角色详情 */
        get: operations["get_role_api_api_v1_system_roles__role_id__get"];
        /** 更新角色 */
        put: operations["update_role_api_api_v1_system_roles__role_id__put"];
        post?: never;
        /** 删除角色 */
        delete: operations["delete_role_api_api_v1_system_roles__role_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 全量权限点（按分组）
         * @description 返回所有权限点，按类别分组（菜单/操作/接口），供角色分配表单用。
         */
        get: operations["list_permissions_api_v1_system_permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 审计日志分页 */
        get: operations["list_audit_logs_api_v1_system_audit_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginIn */
        LoginIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginOut */
        LoginOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserBrief"];
            /**
             * Projects
             * @default []
             */
            projects: components["schemas"]["ProjectBrief"][];
            /**
             * Permissions
             * @default []
             */
            permissions: string[];
        };
        /** MeOut */
        MeOut: {
            user: components["schemas"]["UserBrief"];
            /**
             * Projects
             * @default []
             */
            projects: components["schemas"]["ProjectBrief"][];
            /**
             * Permissions
             * @default []
             */
            permissions: string[];
            /** Current Project Id */
            current_project_id?: number | null;
        };
        /**
         * PermissionGroup
         * @description 按分组整理的权限列表，前端 Checkbox 用。
         */
        PermissionGroup: {
            /**
             * Group
             * @default
             */
            group: string;
            /** Items */
            items?: components["schemas"]["PermissionOut"][];
        };
        /** PermissionOut */
        PermissionOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /**
             * Type
             * @default menu
             */
            type: string;
            /**
             * Parent Id
             * @default 0
             */
            parent_id: number;
            /**
             * Path
             * @default
             */
            path: string;
            /**
             * Icon
             * @default
             */
            icon: string;
            /**
             * Sort
             * @default 0
             */
            sort: number;
        };
        /** ProjectBrief */
        ProjectBrief: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Status
             * @default 1
             */
            status: number;
        };
        /** R */
        R: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Msg
             * @default ok
             */
            msg: string;
            /** Data */
            data?: unknown | null;
        };
        /** R[LoginOut] */
        R_LoginOut_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Msg
             * @default ok
             */
            msg: string;
            data?: components["schemas"]["LoginOut"] | null;
        };
        /** R[MeOut] */
        R_MeOut_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Msg
             * @default ok
             */
            msg: string;
            data?: components["schemas"]["MeOut"] | null;
        };
        /** R[ProjectOut] */
        R_ProjectOut_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Msg
             * @default ok
             */
            msg: string;
            data?: components["schemas"]["ProjectOut"] | null;
        };
        /** R[RoleOut] */
        R_RoleOut_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Msg
             * @default ok
             */
            msg: string;
            data?: components["schemas"]["RoleOut"] | null;
        };
        /** R[UserOut] */
        R_UserOut_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Msg
             * @default ok
             */
            msg: string;
            data?: components["schemas"]["UserOut"] | null;
        };
        /** R[dict] */
        R_dict_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Msg
             * @default ok
             */
            msg: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
        };
        /** R[list] */
        R_list_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Msg
             * @default ok
             */
            msg: string;
            /** Data */
            data?: unknown[] | null;
        };
        /** R[list[PermissionGroup]] */
        R_list_PermissionGroup__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Msg
             * @default ok
             */
            msg: string;
            /** Data */
            data?: components["schemas"]["PermissionGroup"][] | null;
        };
        /** R[list[ProjectOut]] */
        R_list_ProjectOut__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Msg
             * @default ok
             */
            msg: string;
            /** Data */
            data?: components["schemas"]["ProjectOut"][] | null;
        };
        /** R[list[RoleOut]] */
        R_list_RoleOut__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Msg
             * @default ok
             */
            msg: string;
            /** Data */
            data?: components["schemas"]["RoleOut"][] | null;
        };
        /** R[list[UserOut]] */
        R_list_UserOut__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Msg
             * @default ok
             */
            msg: string;
            /** Data */
            data?: components["schemas"]["UserOut"][] | null;
        };
        /** RoleCreate */
        RoleCreate: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /**
             * Data Scope
             * @default project
             */
            data_scope: string;
            /**
             * Remark
             * @default
             */
            remark: string;
            /** Permission Codes */
            permission_codes?: string[];
        };
        /** RoleOut */
        RoleOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /**
             * Data Scope
             * @default project
             */
            data_scope: string;
            /**
             * Remark
             * @default
             */
            remark: string;
            /** Permission Codes */
            permission_codes?: string[];
            /** Created At */
            created_at?: string | null;
        };
        /** RoleUpdate */
        RoleUpdate: {
            /** Name */
            name?: string | null;
            /** Data Scope */
            data_scope?: string | null;
            /** Remark */
            remark?: string | null;
            /** Permission Codes */
            permission_codes?: string[] | null;
        };
        /** UserBrief */
        UserBrief: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /**
             * Nickname
             * @default
             */
            nickname: string;
            /**
             * Email
             * @default
             */
            email: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            /**
             * Password
             * @default 123456
             */
            password: string;
            /**
             * Nickname
             * @default
             */
            nickname: string;
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Status
             * @default 1
             */
            status: number;
            /** Role Codes */
            role_codes?: string[];
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /**
             * Nickname
             * @default
             */
            nickname: string;
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Status
             * @default 1
             */
            status: number;
            /** Role Codes */
            role_codes?: string[];
            /** Created At */
            created_at?: string | null;
            /** Last Login At */
            last_login_at?: string | null;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Username */
            username?: string | null;
            /** Nickname */
            nickname?: string | null;
            /** Email */
            email?: string | null;
            /** Status */
            status?: number | null;
            /** Password */
            password?: string | null;
            /** Role Codes */
            role_codes?: string[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R_LoginOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R_MeOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R_list_ProjectOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_project_api_v1_projects_current_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R_ProjectOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    menus_api_v1_system_menus_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R_list_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_system_users_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R_list_UserOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_system_users_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R_UserOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_api_v1_system_users__user_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: number | null;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R_UserOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_api_v1_system_users__user_id__put: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: number | null;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R_UserOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_api_v1_system_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: number | null;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_api_v1_system_roles_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R_list_RoleOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_role_api_v1_system_roles_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R_RoleOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_role_api_api_v1_system_roles__role_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: number | null;
            };
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R_RoleOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_role_api_api_v1_system_roles__role_id__put: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: number | null;
            };
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R_RoleOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_role_api_api_v1_system_roles__role_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: number | null;
            };
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_permissions_api_v1_system_permissions_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Project-Id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R_list_PermissionGroup__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_logs_api_v1_system_audit_logs_get: {
        parameters: {
            query?: {
                action?: string;
                keyword?: string;
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-Project-Id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["R_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
