/**
 * Generated OpenAPI contract entry point.
 *
 * Runtime API modules should import response types from here instead of
 * re-declaring backend schemas by hand. `api.d.ts` is generated by
 * `npm run gen:api` and remains the single schema source.
 */
import type { components, paths } from '@/types/api'

export type ApiSchema = components['schemas']
export type ApiPath = keyof paths
export type ApiEnvelope<T> = {
  code: number
  msg: string
  data: T
}

export type LoginOut = ApiSchema['LoginOut']
export type PublicAccessOut = ApiSchema['PublicAccessOut']
export type UserOut = ApiSchema['UserOut']
export type UserCreate = ApiSchema['UserCreate']
export type UserUpdate = ApiSchema['UserUpdate']
export type RoleOut = ApiSchema['RoleOut']
export type RoleCreate = ApiSchema['RoleCreate']
export type RoleUpdate = ApiSchema['RoleUpdate']
export type TestCaseOut = ApiSchema['TestCaseOut']
export type TestCaseCreate = ApiSchema['TestCaseCreate']
export type TestCaseUpdate = ApiSchema['TestCaseUpdate']
export type DefectOut = ApiSchema['DefectOut']
export type DefectCreate = ApiSchema['DefectCreate']
export type DefectUpdate = ApiSchema['DefectUpdate']
export type DefectStats = ApiSchema['DefectStats']
export type DashboardStats = ApiSchema['DashboardStats']
export type EnvironmentResponse = ApiSchema['EnvironmentResponse']
export type PlanOut = ApiSchema['PlanOut']
export type PlanDetailOut = ApiSchema['PlanDetailOut']
export type ReportOut = ApiSchema['ReportOut']
export type ReportDetailOut = ApiSchema['ReportDetailOut']
export type ReportCreate = ApiSchema['ReportCreate']




